version: '3'

volumes:
  vocup_local_postgres_data: {}
  vocup_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: sompodbd/vocupdev:vocup_local_django
    container_name: vocup_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "80:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: sompodbd/vocupdev:vocup_production_postgres
    container_name: vocup_local_postgres
    ports:
      - "5432:5432"
    volumes:
      - vocup_local_postgres_data:/var/lib/postgresql/data:Z
      - vocup_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: root # Optional: see below
    volumes:
      - /var/opt/pgbackups:/backups
    links:
      - postgres
    depends_on:
      - django
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=vocup
      - POSTGRES_USER=debug
      - POSTGRES_PASSWORD=debug
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080
