# Generated by Django 3.2.11 on 2022-02-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.CharField(default='', max_length=100),
        ),
    ]
