export const QUIZ_LIST_REQUEST = 'QUIZ_LIST_REQUEST'
export const QUIZ_LIST_SUCCESS = 'QUIZ_LIST_SUCCESS'
export const QUIZ_LIST_FAIL = 'QUIZ_LIST_FAIL'
export const QUIZ_LIST_RESET = 'QUIZ_LIST_RESET'

export const QUIZ_RANGE_LIST_REQUEST = 'QUIZ_RANGE_LIST_REQUEST'
export const QUIZ_RANGE_LIST_SUCCESS = 'QUIZ_RANGE_LIST_SUCCESS'
export const QUIZ_RANGE_LIST_FAIL = 'QUIZ_RANGE_LIST_FAIL'
export const QUIZ_RANGE_LIST_RESET = 'QUIZ_RANGE_LIST_RESET'

export const QUIZ_ANSWER_SUBMIT_REQUEST = 'QUIZ_ANSWER_SUBMIT_REQUEST'
export const QUIZ_ANSWER_SUBMIT_SUCCESS = 'QUIZ_ANSWER_SUBMIT_SUCCESS'
export const QUIZ_ANSWER_SUBMIT_FAIL = 'QUIZ_ANSWER_SUBMIT_FAIL'
export const QUIZ_ANSWER_SUBMIT_RESET = 'QUIZ_ANSWER_SUBMIT_RESET'

// export const QUIZ_WORD_UPDATE_REQUEST = 'QUIZ_WORD_UPDATE_REQUEST'
// export const QUIZ_WORD_UPDATE_SUCCESS = 'QUIZ_WORD_UPDATE_SUCCESS'
// export const QUIZ_WORD_UPDATE_FAIL = 'QUIZ_WORD_UPDATE_FAIL'
// export const QUIZ_WORD_UPDATE_RESET = 'QUIZ_WORD_UPDATE_RESET'

export const QUIZ_LIST_REMOVE_REQUEST = 'QUIZ_LIST_REMOVE_REQUEST'
export const QUIZ_LIST_REMOVE_SUCCESS = 'QUIZ_LIST_REMOVE_SUCCESS'
export const QUIZ_LIST_REMOVE_FAIL = 'QUIZ_LIST_REMOVE_FAIL'
export const QUIZ_LIST_REMOVE_RESET = 'QUIZ_LIST_REMOVE_RESET'
