export const QUIZ_LIST_REQUEST = 'QUIZ_LIST_REQUEST'
export const QUIZ_LIST_SUCCESS = 'QUIZ_LIST_SUCCESS'
export const QUIZ_LIST_FAIL = 'QUIZ_LIST_FAIL'
export const QUIZ_LIST_RESET = 'QUIZ_LIST_RESET'

export const QUIZ_WORD_UPDATE_REQUEST = 'QUIZ_WORD_UPDATE_REQUEST'
export const QUIZ_WORD_UPDATE_SUCCESS = 'QUIZ_WORD_UPDATE_SUCCESS'
export const QUIZ_WORD_UPDATE_FAIL = 'QUIZ_WORD_UPDATE_FAIL'
export const QUIZ_WORD_UPDATE_RESET = 'QUIZ_WORD_UPDATE_RESET'
