export const TUTORIAL_LIST_REQUEST = 'TUTORIAL_LIST_REQUEST'
export const TUTORIAL_LIST_SUCCESS = 'TUTORIAL_LIST_SUCCESS'
export const TUTORIAL_LIST_FAIL = 'TUTORIAL_LIST_FAIL'
export const TUTORIAL_LIST_RESET = 'QUIZ_LIST_RESET'

export const TUTORIAL_CREATE_REQUEST = 'TUTORIAL_CREATE_REQUEST'
export const TUTORIAL_CREATE_SUCCESS = 'TUTORIAL_CREATE_SUCCESS'
export const TUTORIAL_CREATE_FAIL = 'TUTORIAL_CREATE_FAIL'
export const TUTORIAL_CREATE_RESET = 'TUTORIAL_CREATE_RESET'

export const TUTORIAL_RETRIEVE_REQUEST = 'TUTORIAL_RETRIEVE_REQUEST'
export const TUTORIAL_RETRIEVE_SUCCESS = 'TUTORIAL_RETRIEVE_SUCCESS'
export const TUTORIAL_RETRIEVE_FAIL = 'TUTORIAL_RETRIEVE_FAIL'
export const TUTORIAL_RETRIEVE_RESET = 'TUTORIAL_RETRIEVE_RESET'

export const TUTORIAL_LIST_TAGS_REQUEST = 'TUTORIAL_LIST_TAGS'
export const TUTORIAL_LIST_TAGS_SUCCESS = 'TUTORIAL_LIST_TAGS_SUCCESS'
export const TUTORIAL_LIST_TAGS_FAIL = 'TUTORIAL_LIST_TAGS_FAIL'
export const TUTORIAL_LIST_TAGS_RESET = 'TUTORIAL_LIST_TAGS_RESET'
