export const TUTORIAL_LIST_REQUEST = 'TUTORIAL_LIST_REQUEST'
export const TUTORIAL_LIST_SUCCESS = 'TUTORIAL_LIST_SUCCESS'
export const TUTORIAL_LIST_FAIL = 'TUTORIAL_LIST_FAIL'
export const TUTORIAL_LIST_RESET = 'QUIZ_LIST_RESET'
