export const WORD_LIST_REQUEST = "WORD_LIST_REQUEST";
export const WORD_LIST_SUCCESS = "WORD_LIST_SUCCESS";
export const WORD_LIST_FAIL = "WORD_LIST_FAIL";
export const WORD_LIST_RESET = "WORD_LIST_RESET";

export const WORD_DETAIL_REQUEST = "WORD_DETAIL_REQUEST";
export const WORD_DETAIL_SUCCESS = "WORD_DETAIL_SUCCESS";
export const WORD_DETAIL_FAIL = "WORD_DETAIL_FAIL";

export const WORD_CREATE_REQUEST = "WORD_CREATE_REQUEST";
export const WORD_CREATE_SUCCESS = "WORD_CREATE_SUCCESS";
export const WORD_CREATE_FAIL = "WORD_CREATE_FAIL";
export const WORD_CREATE_RESET = "WORD_CREATE_RESET";

export const WORD_DELETE_REQUEST = "WORD_DELETE_REQUEST";
export const WORD_DELETE_SUCCESS = "WORD_DELETE_SUCCESS";
export const WORD_DELETE_FAIL = "WORD_DELETE_FAIL";
export const WORD_DELETE_RESET = "WORD_DELETE_RESET";
