# Generated by Django 3.2.11 on 2022-03-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='repeat_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
