# Generated by Django 3.2.11 on 2022-03-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_repeat_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='repeated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='repeat_every',
            field=models.IntegerField(default=0),
        ),
    ]
